# ================================================================
# MongoDB EC2 Module
#
# Deploys a t4g.micro EC2 instance (Amazon Linux 2023 ARM64) in a
# public subnet with:
#   - MongoDB 7.0 installed and hardened via user data
#   - auth_user  (readWrite on auth_db)
#   - proxy_user (readWrite on proxy_db)
#   - Security group: port 27017 inbound from ECS tasks SG only
#   - IAM role: AmazonSSMManagedInstanceCore (SSM Session Manager,
#     no SSH / bastion needed)
#   - Passwords auto-generated by Terraform random_password
#   - Connection strings written to Secrets Manager automatically
#
# NOTE: The instance sits in a PUBLIC subnet so user data can download
# MongoDB packages from the internet.  The security group blocks all
# inbound traffic except port 27017 from the ECS tasks SG.
# ================================================================

locals {
  name_prefix = "${var.project}-${var.environment}-mongodb"
}

# ── Passwords (alphanumeric, safe to embed in shell scripts) ──────────

resource "random_password" "mongo_admin" {
  length  = 32
  special = false
}

resource "random_password" "auth_db" {
  length  = 32
  special = false
}

resource "random_password" "proxy_db" {
  length  = 32
  special = false
}

# ── Security Group ────────────────────────────────────────────────────

resource "aws_security_group" "mongodb" {
  name        = "${local.name_prefix}-sg"
  description = "Allow MongoDB port 27017 from ECS tasks only"
  vpc_id      = var.vpc_id

  ingress {
    from_port       = 27017
    to_port         = 27017
    protocol        = "tcp"
    security_groups = [var.ecs_tasks_sg_id]
    description     = "MongoDB from ECS tasks"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "${local.name_prefix}-sg" }
}

# ── IAM Role for SSM Session Manager (no SSH needed) ─────────────────

resource "aws_iam_role" "mongodb_ssm" {
  name = "${local.name_prefix}-ssm-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ssm_core" {
  role       = aws_iam_role.mongodb_ssm.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "mongodb" {
  name = "${local.name_prefix}-instance-profile"
  role = aws_iam_role.mongodb_ssm.name
}

# ── Latest Amazon Linux 2023 ARM64 AMI ───────────────────────────────

data "aws_ami" "al2023_arm" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-arm64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ── EC2 Instance ──────────────────────────────────────────────────────

resource "aws_instance" "mongodb" {
  ami                         = data.aws_ami.al2023_arm.id
  instance_type               = var.instance_type
  subnet_id                   = var.subnet_id
  vpc_security_group_ids      = [aws_security_group.mongodb.id]
  iam_instance_profile        = aws_iam_instance_profile.mongodb.name
  associate_public_ip_address = true # required: user data must download MongoDB packages

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    mongo_admin_password = random_password.mongo_admin.result
    auth_db_password     = random_password.auth_db.result
    proxy_db_password    = random_password.proxy_db.result
  })

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    delete_on_termination = true
  }

  tags = { Name = "${local.name_prefix}" }
}

# ── Write connection strings to Secrets Manager ───────────────────────
# These versions are created after the EC2 private IP is known.
# The secrets containers (/chatproxy/dev/mongodb/auth and /proxy)
# were already created by the secrets module.

resource "aws_secretsmanager_secret_version" "mongodb_auth" {
  secret_id = "/${var.project}/${var.environment}/mongodb/auth"
  secret_string = jsonencode({
    MONGODB_URI = "mongodb://auth_user:${random_password.auth_db.result}@${aws_instance.mongodb.private_ip}:27017/auth_db"
  })
}

resource "aws_secretsmanager_secret_version" "mongodb_proxy" {
  secret_id = "/${var.project}/${var.environment}/mongodb/proxy"
  secret_string = jsonencode({
    MONGODB_URL = "mongodb://proxy_user:${random_password.proxy_db.result}@${aws_instance.mongodb.private_ip}:27017/proxy_db"
  })
}
